config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :users
  resources :projects
  resources :expensetypes
  resources :expensestatuses
  resources :expenses
  resources :currencies
end

app/models/ability.rb
class Ability
  include CanCan::Ability

    def initialize( user )
    user ||= User.new

    # Define User abilities
    if user.is? :admin
      can :manage, Expensestatus
      can :manage, Expensetype
      can :manage, Project
      can :manage, Expense
      can :manage, User
      can :manage, Currency
    else
      can :read, Expensestatus
      can :read, Expensetype
      can :read, Project
      can :read, Expense
      can :read, User
      can :read, Currency
    end
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :expensestatus
  belongs_to :expensetype
  belongs_to :currency
end

app/models/expensestatus.rb
class Expensestatus < ActiveRecord::Base
end

app/models/expensetype.rb
class Expensetype < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :expenses
  
  Roles = [ :admin , :default ]

  def is?( requested_role )
    self.role == requested_role.to_s
  end

	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.email = auth.info.email
      user.profileurl = auth.info.image
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)

      if(user.email=='vikasp@sahajsoft.com')
        user.role = 'admin'
      else
        user.role = 'default'
      end

      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
   helper_method :current_user

  # Catch all CanCan errors and alert the user of the exception
  rescue_from CanCan::AccessDenied do | exception |
    redirect_to root_url, alert: exception.message
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
	def index
		@currencies = Currency.all
	end

	def new
		@currency = Currency.new
	end

	def edit
		@currency = Currency.find(params[:id])
	end

	def create
		@currency = Currency.new(currency_params)
		if @currency.save
			redirect_to @currency
		else
			render 'new'
		end
	end

	def update
		@currency = Currency.find(params[:id])
		if(@currency.update(currency_params))
			redirect_to @currency
		else
			render 'edit'
		end
	end

	def destroy
    	@currency = Currency.find(params[:id])
    	@currency.destroy
    	redirect_to currencies_path
  	end

 	def show
    	@currency = Currency.find(params[:id])
    end
	private
  		def currency_params
    		params.require(:currency).permit(:title,  :description)
  		end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	def index
		if (current_user.is? :admin)
			if(params[:expense]!= nil)
				where = {}
				where[:project_id] = params[:expense][:project_id] if params[:expense][:project_id].present?
				where[:currency_id] = params[:expense][:currency_id] if params[:expense][:currency_id].present?
				where[:expensetype_id] = params[:expense][:expensetype_id] if params[:expense][:expensetype_id].present?
				where[:user_id] = params[:expense][:user_id] if params[:expense][:user_id].present?
				where[:expensestatus_id] = params[:expense][:expensestatus_id] if params[:expense][:expensestatus_id].present?
				if((params[:expense][:isbillable].present?)&&(params[:expense][:isbillable]!='-1'))
					where[:isbillable] = params[:expense][:isbillable]
				end
				if((params[:expense][:fromdate].present?)&&(params[:expense][:todate].present?))
					where[:expensedate] = params[:expense][:fromdate]..params[:expense][:todate]
				end

				@expenses = Expense.where(where).paginate(page: params[:page], per_page: 10)
			else
				@expenses = Expense.all.paginate(page: params[:page], per_page: 10)
			end
		else
			if(params[:expense]!= nil)
				where = {}
				where[:project_id] = params[:expense][:project_id] if params[:expense][:project_id].present?
				where[:currency_id] = params[:expense][:currency_id] if params[:expense][:currency_id].present?
				where[:expensetype_id] = params[:expense][:expensetype_id] if params[:expense][:expensetype_id].present?
				where[:expensestatus_id] = params[:expense][:expensestatus_id] if params[:expense][:expensestatus_id].present?
				if((params[:expense][:isbillable].present?)&&(params[:expense][:isbillable]!='-1'))
					where[:isbillable] = params[:expense][:isbillable]
				end
				if((params[:expense][:fromdate].present?)&&(params[:expense][:todate].present?))
					where[:expensedate] = params[:expense][:fromdate]..params[:expense][:todate]
				end

				@expenses = current_user.expenses.where(where).paginate(page: params[:page], per_page: 10)
			else
				@expenses = current_user.expenses.paginate(page: params[:page], per_page: 10)
			end
		end
	end

	def new
		@expense = Expense.new
	end

	def edit
		@expense = Expense.find(params[:id])
	end

	def create
		@expense = Expense.new(expense_params)
		if (current_user.is? :default)
			@expense.user_id = current_user.id
			@expense.expensestatus_id = Expensestatus.first.id
		end
		
		respond_to do |format|
			if @expense.save
				format.json { head :no_content }
	        	format.js
			else
				render 'new'
			end
		end
	end

	def update
		@expense = Expense.find(params[:id])
		respond_to do |format|
			if(@expense.update(expense_params))
				format.json { head :no_content }
	        	format.js
			else
				render 'edit'
			end
		end
	end

	def destroy
    	@expense = Expense.find(params[:id])
    	@expense.destroy
  	end

 	def show
 		@expense = Expense.find(params[:id])
    end
    
	private
  		def expense_params
    		params.require(:expense).permit(:vendor, :amount,  :description, :tag, :expensedate, 
    			:user_id, :project_id, :expensestatus_id, :expensetype_id, :billnumber, :isbillable, :currency_id)
  		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def edit
		@project = Project.find(params[:id])
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to @project
		else
			render 'new'
		end
	end

	def update
		@project = Project.find(params[:id])
		if(@project.update(project_params))
			redirect_to @project
		else
			render 'edit'
		end
	end

	def destroy
    	@project = Project.find(params[:id])
    	@project.destroy
    	redirect_to projects_path
  	end

 	def show
    	@project = Project.find(params[:id])
    end

	private
  		def project_params
    		params.require(:project).permit(:title, :isBillable, :description)
  		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to user_path(user)
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/expensestatuses_helper.rb
module ExpensestatusesHelper
end

app/helpers/expensetypes_helper.rb
module ExpensetypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/currencies/_form.html.erb
<%= form_for @currency do |f| %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/currencies/edit.html.erb
<h1>Edit currency Type</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', currency_path %>

app/views/currencies/index.html.erb
<h1>currency Types</h1>
<%= link_to 'New currency', new_currency_path %>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
 
  <% @currencies.each do |currency| %>
    <tr>
      <td><%= currency.title %></td>
      <td><%= currency.description %></td>
      <td><%= link_to 'Show', currency_path(currency) %></td>
      <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
      <td><%= link_to 'Destroy', currency_path(currency),method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/currencies/new.html.erb
<h1>New currency Type</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @currency.title %>
</p>

 
<p>
  <strong>Description:</strong>
  <%= @currency.description %>
</p>
 
<%= link_to 'Back', currencies_path %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :isBillable %><br>
    <%= f.text_area :isBillable %>
  </p>
  
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<%= link_to 'New Project', new_project_path %>
<table class="table">
  <tr>
    <th>Title</th>
    <th>IsBillable</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
 
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.title %></td>
      <td><%= project.isBillable %></td>
      <td><%= project.description %></td>
      <td><%= link_to 'Show', project_path(project) %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project_path(project),method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>
 
 <p>
  <strong>isBillable:</strong>
  <%= @project.isBillable %>
</p>
 
 
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>
 
<%= link_to 'Back', projects_path %>

app/views/users/show.html.erb
<h1>User Home Page</h1>