config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :users
  resources :projects
  resources :expensetypes
  resources :expensestatuses
  resources :expenses
  resources :currencies
end

app/models/ability.rb
class Ability
  include CanCan::Ability

    def initialize( user )
    user ||= User.new

    # Define User abilities
    if user.is? :admin
      can :manage, Expensestatus
      can :manage, Expensetype
      can :manage, Project
      can :manage, Expense
      can :manage, User
      can :manage, Currency
    else
      can :read, Expensestatus
      can :read, Expensetype
      can :read, Project
      can :read, Expense
      can :read, User
      can :read, Currency
    end
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :expensestatus
  belongs_to :expensetype
  belongs_to :currency
end

app/models/expensestatus.rb
class Expensestatus < ActiveRecord::Base
end

app/models/expensetype.rb
class Expensetype < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :expenses
  
  Roles = [ :admin , :default ]

  def is?( requested_role )
    self.role == requested_role.to_s
  end

	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.email = auth.info.email
      user.profileurl = auth.info.image
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)

      if(user.email=='vikasp@sahajsoft.com')
        user.role = 'admin'
      else
        user.role = 'default'
      end

      user.save!
    end
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
	def index
		@currencies = Currency.all
	end

	def new
		@currency = Currency.new
	end

	def edit
		@currency = Currency.find(params[:id])
	end

	def create
		@currency = Currency.new(currency_params)
		if @currency.save
			redirect_to @currency
		else
			render 'new'
		end
	end

	def update
		@currency = Currency.find(params[:id])
		if(@currency.update(currency_params))
			redirect_to @currency
		else
			render 'edit'
		end
	end

	def destroy
    	@currency = Currency.find(params[:id])
    	@currency.destroy
    	redirect_to currencies_path
  	end

 	def show
    	@currency = Currency.find(params[:id])
    end
	private
  		def currency_params
    		params.require(:currency).permit(:title,  :description)
  		end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	def index
		if (current_user.is? :admin)
			if(params[:expense]!= nil)
				where = {}
				where[:project_id] = params[:expense][:project_id] if params[:expense][:project_id].present?
				where[:currency_id] = params[:expense][:currency_id] if params[:expense][:currency_id].present?
				where[:expensetype_id] = params[:expense][:expensetype_id] if params[:expense][:expensetype_id].present?
				where[:user_id] = params[:expense][:user_id] if params[:expense][:user_id].present?
				where[:expensestatus_id] = params[:expense][:expensestatus_id] if params[:expense][:expensestatus_id].present?
				if((params[:expense][:isbillable].present?)&&(params[:expense][:isbillable]!='-1'))
					where[:isbillable] = params[:expense][:isbillable]
				end
				if((params[:expense][:fromdate].present?)&&(params[:expense][:todate].present?))
					where[:expensedate] = params[:expense][:fromdate]..params[:expense][:todate]
				end

				@expenses = Expense.where(where).paginate(page: params[:page], per_page: 10)
			else
				@expenses = Expense.all.paginate(page: params[:page], per_page: 10)
			end
		else
			if(params[:expense]!= nil)
				where = {}
				where[:project_id] = params[:expense][:project_id] if params[:expense][:project_id].present?
				where[:currency_id] = params[:expense][:currency_id] if params[:expense][:currency_id].present?
				where[:expensetype_id] = params[:expense][:expensetype_id] if params[:expense][:expensetype_id].present?
				where[:expensestatus_id] = params[:expense][:expensestatus_id] if params[:expense][:expensestatus_id].present?
				if((params[:expense][:isbillable].present?)&&(params[:expense][:isbillable]!='-1'))
					where[:isbillable] = params[:expense][:isbillable]
				end
				if((params[:expense][:fromdate].present?)&&(params[:expense][:todate].present?))
					where[:expensedate] = params[:expense][:fromdate]..params[:expense][:todate]
				end

				@expenses = current_user.expenses.where(where).paginate(page: params[:page], per_page: 10)
			else
				@expenses = current_user.expenses.paginate(page: params[:page], per_page: 10)
			end
		end
	end

	def new
		@expense = Expense.new
	end

	def edit
		@expense = Expense.find(params[:id])
	end

	def create
		@expense = Expense.new(expense_params)
		if (current_user.is? :default)
			@expense.user_id = current_user.id
			@expense.expensestatus_id = Expensestatus.first.id
		end
		
		respond_to do |format|
			if @expense.save
				format.json { head :no_content }
	        	format.js
			else
				render 'new'
			end
		end
	end

	def update
		@expense = Expense.find(params[:id])
		respond_to do |format|
			if(@expense.update(expense_params))
				format.json { head :no_content }
	        	format.js
			else
				render 'edit'
			end
		end
	end

	def destroy
    	@expense = Expense.find(params[:id])
    	@expense.destroy
  	end

 	def show
 		@expense = Expense.find(params[:id])
    end
    
	private
  		def expense_params
    		params.require(:expense).permit(:vendor, :amount,  :description, :tag, :expensedate, 
    			:user_id, :project_id, :expensestatus_id, :expensetype_id, :billnumber, :isbillable, :currency_id)
  		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def edit
		@project = Project.find(params[:id])
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to @project
		else
			render 'new'
		end
	end

	def update
		@project = Project.find(params[:id])
		if(@project.update(project_params))
			redirect_to @project
		else
			render 'edit'
		end
	end

	def destroy
    	@project = Project.find(params[:id])
    	@project.destroy
    	redirect_to projects_path
  	end

 	def show
    	@project = Project.find(params[:id])
    end

	private
  		def project_params
    		params.require(:project).permit(:title, :isBillable, :description)
  		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to user_path(user)
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/expensestatuses_helper.rb
module ExpensestatusesHelper
end

app/helpers/expensetypes_helper.rb
module ExpensetypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/expenses/_filter.html.erb
<%= form_tag("/expenses/", method: "get") do %>
        
        <div class="form-group">
          <%= label_tag(:fromdate, "From") %>
          <%= date_field(:expense, :fromdate, :class=> "form-control") %>
        </div>
        <div class="form-group">
          <%= label_tag(:todate, "To") %>
          <%= date_field(:expense, :todate, :class=> "form-control") %>
       </div>
        <div class="form-group">
          <%= label_tag(:project_id, "Project") %>
          <%= collection_select(:expense, :project_id, Project.all, :id, :title, {:prompt => "Select a project"}, {:class=> "form-control"})%>
       </div>
       <div class="form-group">
          <%= label_tag(:currency_id, "Currency") %>
          <%= collection_select(:expense, :currency_id, Currency.all, :id, :title, {:prompt => "Select a currency"}, {:class =>"form-control"})%>
       </div>
       <div class="form-group">
          <%= label_tag(:expensetype_id, "Category") %>
          <%= collection_select(:expense, :expensetype_id, Expensetype.all, :id, :title, {:prompt => "Select a category"}, {:class =>"form-control"})%>
        </div>
        <% if current_user.is? :admin%>
          <div class="form-group">
            <%= label_tag(:user_id, "User") %>
            <%= collection_select(:expense, :user_id, User.all, :id, :name, {:prompt => "Select a user"}, {:class =>"form-control"})%>
         </div>
        <% end %>
        <div class="form-group">
          <%= label_tag(:expensestatus_id, "Status") %>
          <%= collection_select(:expense, :expensestatus_id, Expensestatus.all, :id, :title, {:prompt => "Select a status"}, {:class =>"form-control"})%>
        </div>
        <div class="form-group">
          <%= label_tag(:isbillable, "Project Type") %>
          <%= select(:expense,:isbillable,options_for_select({ "All" => "-1", "Billable" => "t", "Non-Billable" => "f" }),{}, {:class => "form-control"}) %>
        </div>
        <%= submit_tag "Apply Filter", :class=> "btn btn-default"%>
        <%= link_to 'Clear', expenses_path, :class => "btn btn-default" %>
<% end %>

app/views/expenses/_form.html.erb
<%= form_for @expense do |f| %>
  <div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= f.label(:vendor, "Vendor") %>
        <%= f.text_field :vendor, :class=> "form-control"%>
     </div>
     <div class=" form-group col-lg-6 col-md-6 col-sm-12">
        <%= f.label(:expensedate, "Expense Date") %>
        <%= f.date_field :expensedate, :class=> "form-control"%>
     </div>
  </div>

  <div class = "row">
    <div class="form-group col-lg-12 col-md-12 col-sm-12">
      <%= f.label(:billnumber, "Bill Number") %>
      <%= f.text_field :billnumber, :class=> "form-control"%>
     </div>
  </div>

  <div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
      <%= f.label(:currency, "Currency") %>
      <%= f.collection_select :currency_id, Currency.all, :id, :title, {:prompt => "Select a currency"}, {:class =>"form-control"} %>
     </div>
     <div class=" form-group col-lg-6 col-md-6 col-sm-12">
      <%= f.label(:amount, "Amount") %>
      <%= f.text_field :amount, :class=> "form-control"%>
     </div>
  </div>
  
  <div class = "row">
    <div class="form-group col-lg-12 col-md-12 col-sm-12">
      <%= f.check_box :isbillable %>
      <%= f.label(:isbillable, "isbillable") %>
     </div>
  </div>

  <div class = "row">
    <div class="form-group col-lg-12 col-md-12 col-sm-12">
       <%= f.label(:project, "Project") %>
        <%= f.collection_select :project_id, Project.all, :id, :title, {:prompt => "Select Project"}, {:class =>"form-control"} %>
     </div>
  </div>

  <div class = "row">
    <div class="form-group col-lg-12 col-md-12 col-sm-12">
       <%= f.label(:expensetype, "Expense Category") %>
      <%= f.collection_select :expensetype_id, Expensetype.all, :id, :title, {:prompt => "Select Expense Category"}, {:class =>"form-control"} %>
     </div>
  </div>

  <div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= f.label(:description, "Description") %>
        <%= f.text_area :description, :class=> "form-control"%>
     </div>
     <div class=" form-group col-lg-6 col-md-6 col-sm-12">
      <%= f.label(:tag, "tag") %>
      <%= f.text_area :tag, :class=> "form-control"%>
     </div>
  </div>

  <% if current_user.is? :admin%>

    <div class = "row">
      <div class="form-group col-lg-12 col-md-12 col-sm-12">
        <%= f.label(:user, "Requester") %>
        <%= f.collection_select :user_id, User.all, :id, :name, {:prompt => "Select User"}, {:class =>"form-control"} %>
      </div>
    </div>

    <div class = "row">
      <div class="form-group col-lg-12 col-md-12 col-sm-12">
         <%= f.label(:expensestatus, "Status") %>
         <%= f.collection_select :expensestatus_id, Expensestatus.all, :id, :title, {:prompt => "Select Status"}, {:class =>"form-control"} %>
        </div>
    </div>

  <% end %>
  <% if current_user.is? :default%>
    <div class = "row">
      <div class="form-group col-lg-12 col-md-12 col-sm-12">
            <%= f.label(:user, "Requester:")%>
            <%= current_user.name %>
      </div>
    </div>

    <div class = "row">
      <div class="form-group col-lg-12 col-md-12 col-sm-12">
          <%= f.label(:expensestatus, "Status:") %>
          <%= Expensestatus.first.title %>
      </div>
    </div>

  <% end %>

  <div class = "row">
    <div class="form-group col-lg-12 col-md-12 col-sm-12">
        <%= f.submit  @expense.new_record? ? "Create" : "Save", :class => "btn btn-primary" %>
        <%= link_to 'Close', expenses_path,  :class => "btn btn-danger" %>
     </div>
  </div>


<% end %>

app/views/expenses/_show.html.erb
<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:user, "Requester : ") %>
        <%= @expense.user.name %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:vendor, "Vendor : ") %>
        <%= @expense.vendor %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:expensedate, "Expense date : ") %>
        <%= @expense.expensedate %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:billnumber, "Bill Number : ") %>
        <%= @expense.billnumber %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:currency, "Currency : ") %>
        <%= @expense.currency.title %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:amount, "Amount : ") %>
        <%= @expense.amount %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:isbillable, "isBillable : ") %>
        <%= @expense.isbillable %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:project, "Project : ") %>
        <%= @expense.project.title %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:expensetype, "Expense Category : ") %>
        <%= @expense.expensetype.title %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:description, "Description : ") %>
        <%= @expense.description %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:tag, "Tag : ") %>
        <%= @expense.tag %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-6 col-md-6 col-sm-12">
        <%= label(:expensestatus, "Status : ") %>
        <%= @expense.expensestatus.title %>
     </div>
</div>

<div class = "row">
    <div class="form-group col-lg-12 col-md-12 col-sm-12">
         <%= link_to 'Close', expenses_path,  :class => "btn btn-danger pull-right" %>
     </div>
</div>


 

app/views/expenses/create.js.erb
$('#dialog').modal('toggle');
$('#expenses').append('<%= j render (@expense) %>')

app/views/expenses/edit.js.erb
// Add the dialog title
$('#dialog h3').html("Expense");
 
// Render the edit form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/expenses/index.html.erb
<div class ="row main_box">
<div class = "col-lg-2 col-md-2 app_panel">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading test">Filters</div>
    <div class="panel-body">
      <%= render 'filter' %>

    </div>
  </div>
</div>
<div class = "col-lg-10 col-md-10 app_panel">
  <div class="panel panel-default">
  <div class="panel-heading">Expenses</div>
  <div class="panel-body">
    <%= link_to 'New Expense', new_expense_path, remote: true, :class => "btn btn-primary" %>
  </div>

  <table class="table sortable">
    <tr>
      <th>Number</th>  
      <th>Vendor</th>
      <th>Bill Number</th>
      <th>Bill Date</th>
      <th>Currency</th>
      <th>Amount</th>
      <th>Description</th>
      <th>Tags</th>
      <th>User</th>
      <th>Billable</th>
      <th>Project</th>
      <th>Status</th>
      <th>Category</th>
      <th></th>
    </tr>
   
    <% @expenses.each do |expense| %>
      <tr>
        <% if current_user.is? :admin%>
          <td>
            <%= link_to '#', edit_expense_path(expense), remote: true%><%= link_to expense.id, edit_expense_path(expense), remote: true %>
          </td>
        <%else%>
          <% if expense.expensestatus.title == Expensestatus.first.title%>
              <td>
                <%= link_to '#', edit_expense_path(expense), remote: true%><%= link_to expense.id, edit_expense_path(expense), remote: true %>
              </td>
          <%else%>
              <td>
                <%= link_to '#', expense_path(expense), remote: true%><%= link_to expense.id, expense_path(expense), remote: true %>
              </td>
          <%end%>
        <%end%>
              
        <td><%= expense.vendor %></td>
        <td><%= expense.billnumber %></td>
        <td><%= expense.expensedate %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.currency.title %></td>
        <td><%= expense.description %></td>
        <td><%= expense.tag %></td>
        <td><%= expense.user.name %></td>
        <td><%= expense.isbillable %></td>
        <td><%= expense.project.title %></td>
        <td><%= expense.expensestatus.title %></td>
        <td><%= expense.expensetype.title %></td>
        <td>
           <% if ((expense.expensestatus==Expensestatus.first)||(current_user.is? :admin))%>
              <%= link_to '', expense_path(expense),method: :delete, data: { confirm: 'Are you sure?' }, :class => "glyphicon glyphicon-trash" %>
            <%end%>
        </td>

      </tr>
    <% end %>
  </table>
  <div class="pull-right">
    <%= will_paginate @expenses, renderer: BootstrapPagination::Rails %>
  </div>

</div>
</div>
</div>
 <%= render 'dialog' %>
  

app/views/expenses/new.js.erb
// Add the dialog title
$('#dialog h3').html("New Expense");
 
// Render the new form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/expenses/show.html.erb
<p>
  <strong>Vendor:</strong>
  <%= @expense.vendor %>
</p>

<p>
  <strong>billNumber:</strong>
  <%= @expense.billnumber %>
</p>

<p>
  <strong>currency:</strong>
  <%= @expense.currency.title %>
</p>

<p>
  <strong>amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>tag:</strong>
  <%= @expense.tag %>
</p>

<p>
  <strong>user:</strong>
  <%= @expense.user.name %>
</p>

<p>
  <strong>isBillable:</strong>
  <%= @expense.isbillable %>
</p>

<p>
  <strong>project:</strong>
  <%= @expense.project.title %>
</p>

<p>
  <strong>expensestatus:</strong>
  <%= @expense.expensestatus.title %>
</p>

<p>
  <strong>expensetype:</strong>
  <%= @expense.expensetype.title %>
</p>
  
 
<%= link_to 'Back', expenses_path %>

app/views/expenses/show.js.erb
// Add the dialog title
$('#dialog h3').html("Expense");
 
// Render the edit form
$('.modal-body').html('<%= j render("show") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");

app/views/expenses/update.js.erb
$('#dialog').modal('toggle');
$('#expense_<%= @expense.id %>').replaceWith('<%= j render (@expense) %>')

app/views/home/show.html.erb
<h1>Home</h1>