config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :users
  resources :projects
  resources :expensetypes
  resources :expensestatuses
  resources :expenses
  resources :currencies
end

app/models/ability.rb
class Ability
  include CanCan::Ability

    def initialize( user )
    user ||= User.new

    # Define User abilities
    if user.is? :admin
      can :manage, Expensestatus
      can :manage, Expensetype
      can :manage, Project
      can :manage, Expense
      can :manage, User
      can :manage, Currency
    else
      can :read, Expensestatus
      can :read, Expensetype
      can :read, Project
      can :read, Expense
      can :read, User
      can :read, Currency
    end
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :expensestatus
  belongs_to :expensetype
  belongs_to :currency
end

app/models/expensestatus.rb
class Expensestatus < ActiveRecord::Base
end

app/models/expensetype.rb
class Expensetype < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :expenses
  
  Roles = [ :admin , :default ]

  def is?( requested_role )
    self.role == requested_role.to_s
  end

	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.email = auth.info.email
      user.profileurl = auth.info.image
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)

      if(user.email=='vikasp@sahajsoft.com')
        user.role = 'admin'
      else
        user.role = 'default'
      end

      user.save!
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	def index
		if (current_user.is? :admin)
			if(params[:expense]!= nil)
				where = {}
				where[:project_id] = params[:expense][:project_id] if params[:expense][:project_id].present?
				where[:currency_id] = params[:expense][:currency_id] if params[:expense][:currency_id].present?
				where[:expensetype_id] = params[:expense][:expensetype_id] if params[:expense][:expensetype_id].present?
				where[:user_id] = params[:expense][:user_id] if params[:expense][:user_id].present?
				where[:expensestatus_id] = params[:expense][:expensestatus_id] if params[:expense][:expensestatus_id].present?
				if((params[:expense][:isbillable].present?)&&(params[:expense][:isbillable]!='-1'))
					where[:isbillable] = params[:expense][:isbillable]
				end
				if((params[:expense][:fromdate].present?)&&(params[:expense][:todate].present?))
					where[:expensedate] = params[:expense][:fromdate]..params[:expense][:todate]
				end

				@expenses = Expense.where(where).paginate(page: params[:page], per_page: 10)
			else
				@expenses = Expense.all.paginate(page: params[:page], per_page: 10)
			end
		else
			if(params[:expense]!= nil)
				where = {}
				where[:project_id] = params[:expense][:project_id] if params[:expense][:project_id].present?
				where[:currency_id] = params[:expense][:currency_id] if params[:expense][:currency_id].present?
				where[:expensetype_id] = params[:expense][:expensetype_id] if params[:expense][:expensetype_id].present?
				where[:expensestatus_id] = params[:expense][:expensestatus_id] if params[:expense][:expensestatus_id].present?
				if((params[:expense][:isbillable].present?)&&(params[:expense][:isbillable]!='-1'))
					where[:isbillable] = params[:expense][:isbillable]
				end
				if((params[:expense][:fromdate].present?)&&(params[:expense][:todate].present?))
					where[:expensedate] = params[:expense][:fromdate]..params[:expense][:todate]
				end

				@expenses = current_user.expenses.where(where).paginate(page: params[:page], per_page: 10)
			else
				@expenses = current_user.expenses.paginate(page: params[:page], per_page: 10)
			end
		end
	end

	def new
		@expense = Expense.new
	end

	def edit
		@expense = Expense.find(params[:id])
	end

	def create
		@expense = Expense.new(expense_params)
		if (current_user.is? :default)
			@expense.user_id = current_user.id
			@expense.expensestatus_id = Expensestatus.first.id
		end
		
		respond_to do |format|
			if @expense.save
				format.json { head :no_content }
	        	format.js
			else
				render 'new'
			end
		end
	end

	def update
		@expense = Expense.find(params[:id])
		respond_to do |format|
			if(@expense.update(expense_params))
				format.json { head :no_content }
	        	format.js
			else
				render 'edit'
			end
		end
	end

	def destroy
    	@expense = Expense.find(params[:id])
    	@expense.destroy
  	end

 	def show
 		@expense = Expense.find(params[:id])
    end
    
	private
  		def expense_params
    		params.require(:expense).permit(:vendor, :amount,  :description, :tag, :expensedate, 
    			:user_id, :project_id, :expensestatus_id, :expensetype_id, :billnumber, :isbillable, :currency_id)
  		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def edit
		@project = Project.find(params[:id])
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to @project
		else
			render 'new'
		end
	end

	def update
		@project = Project.find(params[:id])
		if(@project.update(project_params))
			redirect_to @project
		else
			render 'edit'
		end
	end

	def destroy
    	@project = Project.find(params[:id])
    	@project.destroy
    	redirect_to projects_path
  	end

 	def show
    	@project = Project.find(params[:id])
    end

	private
  		def project_params
    		params.require(:project).permit(:title, :isBillable, :description)
  		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/expensestatuses_helper.rb
module ExpensestatusesHelper
end

app/helpers/expensetypes_helper.rb
module ExpensetypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Google Auth Example App</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Prabandhak</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <% if can? :manage, Project %>
                <li ><%= link_to 'Projects', controller: 'projects' %></li>
              <% end %>

              <% if can? :manage, Expensetype %>
                <li ><%= link_to 'Expense Category', controller: 'expensetypes' %></li>
              <% end %>

              <% if can? :manage, Expensestatus %>
               <li  ><%= link_to 'Workflow', controller: 'expensestatuses' %></li>
              <% end %>

              <% if can? :manage, Currency %>
                <li><%= link_to 'Currency', controller: 'currencies' %></li>
              <% end %>

              <li><%= link_to 'Expenses', controller: 'expenses' %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>
                <%= link_to root_url do %>
                  <%= image_tag current_user.profileurl, height: '40', width: '40'%>
                <% end %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <% if current_user.is? :admin%>
                    <strong>Admin : </strong>
                  <%end%>
                  <strong><%= current_user.name %></strong>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="#">Dashboard</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign in", "/auth/google_oauth2", id: "sign_in" %></li>
            <% end %> 
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div>
      <%= yield %>
    </div>
  </body>
</html>